version: "3.8"
services:
  buildingdb:
    image: mongo
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:management
  identity.api:
    image: identity_api_image
    build:
      context: .
      dockerfile: Identity/AdminPanel.Identity.API/Dockerfile
  building-command.api:
    image: building-command_api_image
    build:
      context: .
      dockerfile: BuildingConfiguration/Command/AdminPanel.BuildingConfiguration.Command.API/Dockerfile
  building-query.api:
    image: building-query_api_image
    build:
      context: .
      dockerfile: BuildingConfiguration/Query/AdminPanel.BuildingConfiguration.Query.API/Dockerfile
volumes:
  buildingdb_volume:
  identitydb_volume:
