version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      - adminpanelnet
  
  identity_api:
    build:
      context: .
      dockerfile: Dockerfile.Identity
    ports:
      - "5218:80"
    depends_on:
      - sqlserver_db
    networks:
      - adminpanelnet

  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password12*"
    ports:
      - "1499:1433"
    networks:
      - adminpanelnet

  command_api:
    build:
      context: .
      dockerfile: Dockerfile.BuildingConfiguration.Command
    ports:
      - "5228:80"
    depends_on:
      - mongodb
    networks:
      - adminpanelnet

  query_api:
    build:
      context: .
      dockerfile: Dockerfile.BuildingConfiguration.Query
    ports:
      - "5129:80"
    depends_on:
      - mongodb
    networks:
      - adminpanelnet

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - adminpanelnet

volumes:
  mongodata:
  rabbitmq_data:

networks:
  adminpanelnet:
    driver: bridge